name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Replace includes
      run: |
        find . -name '*.html' -exec sed -i -e '/<!--#include file=/!b' -e ':a' -e 'N' -e '$!ba' -e "s/<!--#include file=\"\([^\"]*\)\" -->/$(cat \1 | sed -e 's/[\/&]/\\&/g')/" {} \;

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
